### ISSUE TITLE
Changing graph flag values

### ISSUE THREAD

**Issue by sadrasabouri** [sepandhaghighi/pyrgg#69]
#### Description
In main menu each flag assigned by `1` or `2`, but it seems more friendly if it changes to `0` or `1`.
In second situation debugging may be more easy.
This issue may include these flags:
+ `weighted`
+ `direct`
+ `self_loop`
+ `multigraph` (which can be changed to `singlegraph` to seems more ordered)

**Comment by sepandhaghighi** [comment]
@ahmadsalimi Do you have any interest to work on this issue after #68?

**Comment by ahmadsalimi** [comment]
> @ahmadsalimi Do you have any interest to work on this issue after #68?

@sepandhaghighi
I will work on this. But, I have a question. Why shouldn't we use `boolean` values for flags?

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi
> I will work on this. But, I have a question. Why shouldn't we use `boolean` values for flags?

There is no difference at all. But mostly it's because of user inputs and function parameters be sync.
I suggest `0` and `1`

**Comment by ahmadsalimi** [comment]
> There is no difference at all. But mostly it's because of user inputs and function parameters be sync.
> I suggest `0` and `1`

@sepandhaghighi I think it is better to use `boolean` according to the **clean code concepts** and **readability** of the code; because we are literally using some `integer` variables as `boolean` values.

Moreover, it's not good for code logic to depend on something related to the user interface. This is the **user interface**'s problem, and the user interface must adapt itself to the code logic. (Because it will be possible (in the future) to use code logic without using the user interface, and we should consider the code logic independently.) For example, the user interface gets 0 or 1 input from the user, then convert it instantly to a boolean value.

This is my opinion, but I'll do it as you think is better.

**Comment by sepandhaghighi** [comment]
@ahmadsalimi
Why you delete your comment?
Please do what you think it's better, I'm waiting for your PR 💯

**Comment by ahmadsalimi** [comment]
> @ahmadsalimi
> I received your removed comment email.
> Please do what you think it's better, I'm waiting for your PR 💯

@sepandhaghighi 😄😄😄😄😄😄😄😄😄

Thank you Sepand, I'm working on it.
